const weatherMapping = {
  0: "Cerah",
  1: "Cerah Berawan",
  2: "Berawan",
  3: "Mendung/Awan Tebal",
  45: "Kabut",
  48: "Kabut Berembun",
  51: "Gerimis Ringan",
  53: "Gerimis Sedang",
  55: "Gerimis Lebat",
  56: "Gerimis Beku Ringan",
  57: "Gerimis Beku Lebat",
  61: "Hujan Ringan",
  63: "Hujan Sedang",
  65: "Hujan Lebat",
  66: "Hujan Beku Ringan",
  67: "Hujan Beku Lebat",
  71: "Hujan Salju Ringan",
  73: "Hujan Salju Sedang",
  75: "Hujan Salju Lebat",
  77: "Butiran Salju",
  80: "Hujan Guyur Ringan",
  81: "Hujan Guyur Sedang",
  82: "Hujan Guyur Sangat Lebat",
  85: "Hujan Salju Ringan",
  86: "Hujan Salju Lebat",
  95: "Badai Petir",
  96: "Badai Petir dengan Hujan Es Ringan",
  99: "Badai Petir dengan Hujan Es Lebat",
};
